/* eslint-disable import/prefer-default-export */
export { default as EdgeForm } from './EdgeForm.vue'
export { default as Loading } from './Loading.vue'
export { default as DateEdit } from './form/DateEdit.vue'
export { default as ModelAutocomplete } from './form/ModelAutocomplete.vue'
export { default as States } from './form/States.vue'
export { default as SwitchEdit } from './form/SwitchEdit.vue'
export { default as TextareaEdit } from './form/TextareaEdit.vue'
export { default as TextAreaReadOnly } from './form/TextAreaReadOnly.vue'
export { default as TextEdit } from './form/TextEdit.vue'
export { default as Money } from './form/Money.vue'
export { default as MoneyRaw } from './form/MoneyRaw.vue'
export { default as Phone } from './form/Phone.vue'
export { default as TextReadOnly } from './form/TextReadOnly.vue'
export { default as SelectEdit } from './form/SelectEdit.vue'
export { default as Time } from './form/Time.vue'
export { default as Wysiwyg } from './form/Wysiwyg.vue'